# Publish multiple messages to a topic
POST http://localhost:3500/v1.0-alpha1/publish/bulk/pubsub/bulk-examples
Content-Type: application/json

[
    {
        "entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002",
        "event":  "first text message",
        "contentType": "text/plain"
    },
    {
        "entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002",
        "event":  {
            "message": "second JSON message"
        },
        "contentType": "application/json"
    }
]

###

# Publish multiple messages to a topic with raw payload (without cloudevent)
POST http://localhost:3500/v1.0-alpha1/publish/bulk/pubsub/bulk-examples?metadata.rawPayload=true
Content-Type: application/json

[
    {
        "entryId": "ae6bf7c6-4af2-11ed-b878-0242ac120002",
        "event":  "first text message",
        "contentType": "text/plain"
    },
    {
        "entryId": "b1f40bd6-4af2-11ed-b878-0242ac120002",
        "event":  {
            "message": "second JSON message"
        },
        "contentType": "application/json"
    }
]