apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisherapp
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisherapp"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: publisher
          image: ghcr.io/shubham1172/kubecon-demo/simple-pubsub:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
