apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisherapp
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisherapp"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: publisher
          image: ghcr.io/shubham1172/kubecon-demo/simple-pubsub-publisher:0.1.0
          imagePullPolicy: Always
          env:
            - name: PUBSUB_NAME
              value: "redis-pubsub"
            - name: TOPIC_NAME
              value: "orders"
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.5"
              memory: 500Mi
